
backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - file: "content/settings.json"
        label: "General"
        name: "general"
        fields:
          - {label: "Mailing List URL", name: "mailingListUrl", widget: "string"}
          - {label: "Contact Email", name: "contactEmail", widget: "string"}
          - label: "Social Links"
            name: "socials"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "URL", name: "href", widget: "string"}

  - name: "music"
    label: "Music"
    files:
      - file: "content/music.json"
        label: "Tracks"
        name: "tracks"
        fields:
          - label: "Tracks"
            name: "tracks"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Platform (YouTube/Bandcamp/SoundCloud)", name: "platform", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}

  - name: "shows"
    label: "Shows"
    files:
      - file: "content/shows.json"
        label: "Upcoming Shows"
        name: "shows"
        fields:
          - label: "Shows"
            name: "shows"
            widget: "list"
            fields:
              - {label: "Date (YYYY-MM-DD)", name: "date", widget: "string"}
              - {label: "Venue", name: "venue", widget: "string"}
              - {label: "City", name: "city", widget: "string"}
              - {label: "Tickets URL", name: "tickets", widget: "string", required: false}

  - name: "photos"
    label: "Photos"
    files:
      - file: "content/gallery.json"
        label: "Gallery"
        name: "gallery"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            field: {label: "Image", name: "image", widget: "image"}

  - name: "epk"
    label: "EPK"
    files:
      - file: "content/epk.json"
        label: "Press Kit"
        name: "presskit"
        fields:
          - {label: "Short Bio", name: "shortBio", widget: "text"}
          - {label: "Long Bio", name: "longBio", widget: "text"}
          - label: "Press Quotes"
            name: "pressQuotes"
            widget: "list"
            fields:
              - {label: "Quote", name: "text", widget: "text"}
              - {label: "Source", name: "source", widget: "string"}
          - label: "Downloads"
            name: "downloads"
            widget: "object"
            fields:
              - {label: "Stage Plot (URL)", name: "stagePlot", widget: "string", required: false}
              - {label: "Tech Spec (URL)", name: "techSpec", widget: "string", required: false}
              - {label: "Press Photos (URL)", name: "pressPhotos", widget: "string", required: false}

  - name: "blog"
    label: "Blog Posts"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Snippet", name: "snippet", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog_list"
    label: "Blog List (for blog homepage)"
    files:
      - file: "blog/posts.json"
        label: "Posts List"
        name: "postslist"
        fields:
          - label: "Posts"
            name: "posts"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Date (YYYY-MM-DD)", name: "date", widget: "string"}
              - {label: "Slug (match filename without .html)", name: "slug", widget: "string"}
              - {label: "Snippet", name: "snippet", widget: "string", required: false}
